apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-spring-boot-app-cicd
  title: sample-spring-boot-app-cicd
  annotations:
    circleci.com/project-slug: github/piomin/sample-spring-boot-app-cicd
    github.com/project-slug: piomin/sample-spring-boot-app-cicd
    sonarqube.org/project-key: piomin_sample-spring-boot-app-cicd
  tags:
    - spring-boot
    - java
    - maven
    - circleci
    - renovate
    - sonarqube
spec:
  type: service
  owner: piotr.minkowski@gmail.com
  lifecycle: experimental